name: Latest
run-name: Building imagefc/alpine:${{ github.event.inputs.version }} (as latest)
on:
  workflow_dispatch:
    inputs:
      version:
        description: alpine version
        required: true
        default: '3.18'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        build-args: |
          version=${{ github.event.inputs.version }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ github.repository }}:${{ github.event.inputs.version }},${{ github.repository }}:latest
        cache-from: type=registry,ref=imagefc/alpine:${{ github.event.inputs.version }}
        cache-to: type=inline
    - name: Build and push bash version
      uses: docker/build-push-action@v4
      with:
        build-args: |
          version=${{ github.event.inputs.version }}
        push: ${{ github.event_name != 'pull_request' }}
        file: bash.Dockerfile
        tags: ${{ github.repository }}:${{ github.event.inputs.version }}-bash
        cache-from: type=registry,ref=imagefc/alpine:${{ github.event.inputs.version }}
        cache-to: type=inline
