name: CI
run-name: Building alpine ${{ vars.version }}
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        build-args: |
          version=${{ vars.version }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ github.repository }}:${{ vars.version }}
    - name: Build and push bash version
      uses: docker/build-push-action@v4
      with:
        build-args: |
          version=${{ vars.version }}
        push: ${{ github.event_name != 'pull_request' }}
        file: bash.Dockerfile
        tags: ${{ github.repository }}:${{ vars.version }}-bash
    
      
    
        
    